name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        pip install -r requirements.txt
    
    - name: Run tests
      run: |
        python -m unittest discover tests/
  
  build-and-push:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    
    - name: Build and push
      uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/flask-app:latest
    
  update-gitops:
    needs: build-and-push
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
      with:
        repository: ${{ secrets.GITOPS_REPO }}
        token: ${{ secrets.PAT_TOKEN }}
        ref: 'main'
        path: gitops-repo
    
    - name: Update image tag if changed
      id: update-tag
      run: |
        cd gitops-repo/overlays/production
        git config user.name "github-actions"
        git config user.email "github-actions@github.com"
        
        # Get current values
        CURRENT_IMAGE=$(yq eval '.images[0].newName' kustomization.yaml)
        CURRENT_TAG=$(yq eval '.images[0].newTag' kustomization.yaml)
        DESIRED_IMAGE="${{ secrets.DOCKER_USERNAME }}/flask-app"
        DESIRED_TAG="${{ github.sha }}"
        
        echo "Current: $CURRENT_IMAGE:$CURRENT_TAG"
        echo "Desired: $DESIRED_IMAGE:$DESIRED_TAG"
        
        # Check if update is needed
        if [ "$CURRENT_IMAGE" != "$DESIRED_IMAGE" ] || [ "$CURRENT_TAG" != "$DESIRED_TAG" ]; then
          yq eval ".images[0].newName = \"$DESIRED_IMAGE\"" -i kustomization.yaml
          yq eval ".images[0].newTag = \"$DESIRED_TAG\"" -i kustomization.yaml
          echo "::set-output name=changes_made::true"
          echo "✅ Updated kustomization.yaml"
        else
          echo "::set-output name=changes_made::false"
          echo "✅ No changes needed"
        fi
        
        echo "Final content:"
        cat kustomization.yaml
    
    - name: Commit and push changes
      if: steps.update-tag.outputs.changes_made == 'true'
      run: |
        cd gitops-repo
        git config user.name "github-actions"
        git config user.email "github-actions@github.com"
        git add .
        git commit -m "CI: Update deployment to ${{ secrets.DOCKER_USERNAME }}/flask-app:${{ github.sha }}"
        git push origin main
        echo "✅ Changes committed and pushed"
    
    - name: Skip commit if no changes
      if: steps.update-tag.outputs.changes_made == 'false'
      run: |
        echo "✅ No changes to commit - skipping git operations"
