name: CI Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        pip install -r requirements.txt
    
    - name: Run tests
      run: |
        python -m unittest discover tests/
  
  build-and-push:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    
    - name: Build and push
      uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/flask-app:${{ github.sha }} 
    
  update-gitops:
    needs: build-and-push
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout GitOps repo with deploy key
      uses: actions/checkout@v3
      with:
        repository: ${{ secrets.GITOPS_REPO }}
        ssh-key: ${{ secrets.DEPLOY_KEY }}
        ref: 'main'
        path: gitops-repo
    
    - name: Configure Git for deploy key
      if: steps.update-tag.outputs.changes_made == 'true'
      run: |
        cd gitops-repo
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git remote set-url origin git@github.com:${{ secrets.GITOPS_REPO }}.git
  
    - name: Commit and push changes
      if: steps.update-tag.outputs.changes_made == 'true'
      run: |
        cd gitops-repo
        git add .
        git commit -m "CI: Update deployment to ${{ secrets.DOCKER_USERNAME }}/flask-app:${{ github.sha }}"
        git push origin main
        echo "✅ Changes committed and pushed"
